"""Configuration package for CodeRabbit Comment Fetcher."""

from .constants import (
    DEFAULT_AI_ROLE,
    DEFAULT_ANALYSIS_METHODOLOGY,
    DEFAULT_CORE_PRINCIPLES,
    DEFAULT_PROGRESS_STEPS,
    DEFAULT_RESOLVED_MARKER,
    DEFAULT_RETRY_ATTEMPTS,
    DEFAULT_RETRY_DELAY,
    DEFAULT_TIMEOUT_SECONDS,
    DEFAULT_TOTAL_OPERATIONS,
    MIN_TIMEOUT_WARNING_THRESHOLD,
    QUIET_MODE_LOG_MODULES,
    SUPPORTED_OUTPUT_FORMATS,
    ZERO_OR_NEGATIVE_ERROR_MSG,
)

__all__ = [
    "DEFAULT_AI_ROLE",
    "DEFAULT_ANALYSIS_METHODOLOGY",
    "DEFAULT_CORE_PRINCIPLES",
    "DEFAULT_PROGRESS_STEPS",
    "DEFAULT_RESOLVED_MARKER",
    "DEFAULT_RETRY_ATTEMPTS",
    "DEFAULT_RETRY_DELAY",
    "DEFAULT_TIMEOUT_SECONDS",
    "DEFAULT_TOTAL_OPERATIONS",
    "MIN_TIMEOUT_WARNING_THRESHOLD",
    "QUIET_MODE_LOG_MODULES",
    "SUPPORTED_OUTPUT_FORMATS",
    "ZERO_OR_NEGATIVE_ERROR_MSG",
]
