"""Configuration package for CodeRabbit Comment Fetcher."""

from .constants import (
    DEFAULT_RESOLVED_MARKER,
    DEFAULT_AI_ROLE,
    DEFAULT_CORE_PRINCIPLES,
    DEFAULT_ANALYSIS_METHODOLOGY,
    DEFAULT_PROGRESS_STEPS,
    SUPPORTED_OUTPUT_FORMATS,
    QUIET_MODE_LOG_MODULES,
    DEFAULT_TOTAL_OPERATIONS,
    DEFAULT_TIMEOUT_SECONDS,
    DEFAULT_RETRY_ATTEMPTS,
    DEFAULT_RETRY_DELAY,
    MIN_TIMEOUT_WARNING_THRESHOLD,
    ZERO_OR_NEGATIVE_ERROR_MSG
)

__all__ = [
    'DEFAULT_RESOLVED_MARKER',
    'DEFAULT_AI_ROLE',
    'DEFAULT_CORE_PRINCIPLES',
    'DEFAULT_ANALYSIS_METHODOLOGY',
    'DEFAULT_PROGRESS_STEPS',
    'SUPPORTED_OUTPUT_FORMATS',
    'QUIET_MODE_LOG_MODULES',
    'DEFAULT_TOTAL_OPERATIONS',
    'DEFAULT_TIMEOUT_SECONDS',
    'DEFAULT_RETRY_ATTEMPTS',
    'DEFAULT_RETRY_DELAY',
    'MIN_TIMEOUT_WARNING_THRESHOLD',
    'ZERO_OR_NEGATIVE_ERROR_MSG'
]